<?php

declare(strict_types=1);

/* ==========================================================================
   Generated Domain Contracts & PHP DTOs
   Feature: Checkout Autenticado con Laravel Sanctum e Inertia Vue
   Stack: PHP 8.2 + laravel + pdo
   Generated by gherkin-ai CLI v3.0.0-beta.1
   ========================================================================== */

namespace App\Domain\Contracts\CheckoutAutenticadoConLaravelSanctumEInertiaVue;

use DateTimeImmutable;

// --------------------------------------------------------------------------
// 1. Base Domain Event Interface
// --------------------------------------------------------------------------
interface IDomainEvent
{
    public function getEventId(): string;
    public function getOccurredOn(): DateTimeImmutable;
    public function getEventType(): string;
}



// --------------------------------------------------------------------------
// 2. Command DTO Class (Readonly PHP 8.2)
// --------------------------------------------------------------------------
readonly class CheckoutAutenticadoConLaravelSanctumEInertiaVueCommand
{
    public function __construct(
        public string $requestId,
        public DateTimeImmutable $timestamp,
        public array $payload
    ) {}
}

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
interface ICheckoutAutenticadoConLaravelSanctumEInertiaVueRepository
{
    public function findById(string $id): mixed;
    public function save(mixed $entity): void;
    public function delete(string $id): void;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
interface IEventPublisher
{
    public function publish(IDomainEvent $event): void;
}
