<?php

declare(strict_types=1);

namespace App\Domain\CheckoutAutenticadoConLaravelSanctumEInertiaVue;

use DateTimeImmutable;

/**
 * Domain kernel for "Checkout Autenticado con Laravel Sanctum e Inertia Vue" (generated by gherkin-ai).
 * Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
 */
final class CheckoutAutenticadoConLaravelSanctumEInertiaVueAggregate
{
    private CheckoutAutenticadoConLaravelSanctumEInertiaVueState $state = CheckoutAutenticadoConLaravelSanctumEInertiaVueState::Pending;
    private int $version = 0;
    /** @var list<CheckoutAutenticadoConLaravelSanctumEInertiaVueDomainEvent> */
    private array $pendingEvents = [];

    public function __construct(private readonly string $id)
    {
        if (trim($id) === '') {
            throw new DomainValidationException('CheckoutAutenticadoConLaravelSanctumEInertiaVue id is required');
        }
    }

    /** Rebuilds an aggregate from persisted state; no events are recorded. */
    public static function restore(string $id, CheckoutAutenticadoConLaravelSanctumEInertiaVueState $state, int $version): self
    {
        $aggregate = new self($id);
        $aggregate->state = $state;
        $aggregate->version = $version;
        return $aggregate;
    }

    public function id(): string { return $this->id; }
    public function state(): CheckoutAutenticadoConLaravelSanctumEInertiaVueState { return $this->state; }
    public function version(): int { return $this->version; }

    /** @return list<CheckoutAutenticadoConLaravelSanctumEInertiaVueDomainEvent> Events recorded since load (to be saved via the outbox). */
    public function pendingEvents(): array { return $this->pendingEvents; }

    public function processCheckoutAutenticadoConLaravelSanctumEInertiaVue(CheckoutAutenticadoConLaravelSanctumEInertiaVueCommand $command): CheckoutAutenticadoConLaravelSanctumEInertiaVueDomainEvent
    {
        $this->assertValid($command);
        return $this->record(CheckoutAutenticadoConLaravelSanctumEInertiaVueEventType::ProcessCheckoutAutenticadoConLaravelSanctumEInertiaVueCompleted, $command->payload);
    }

    private function assertValid(CheckoutAutenticadoConLaravelSanctumEInertiaVueCommand $command): void
    {
        if (trim($command->id) === '') {
            throw new DomainValidationException('Command id is required');
        }
        if ($command->id !== $this->id) {
            throw new DomainValidationException("Command targets {$command->id}, not {$this->id}");
        }
    }

    /** @param array<string, mixed> $payload */
    private function record(CheckoutAutenticadoConLaravelSanctumEInertiaVueEventType $type, array $payload): CheckoutAutenticadoConLaravelSanctumEInertiaVueDomainEvent
    {
        $this->version++;
        $event = new CheckoutAutenticadoConLaravelSanctumEInertiaVueDomainEvent($type, $this->id, $this->version, new DateTimeImmutable(), $payload);
        $this->pendingEvents[] = $event;
        return $event;
    }
}
