// API client for "Checkout Autenticado con Laravel Sanctum e Inertia Vue" (generated by gherkin-ai).
// Contract: POST /api/v1/checkout-autenticado-con-laravel-sanctum-e-inertia-vue/{id}/{command} -> 201 { type, aggregateId, version }

export const COMMANDS = ['process_checkout_autenticado_con_laravel_sanctum_e_inertia_vue'] as const;
export type CommandName = (typeof COMMANDS)[number];

export interface CommandResult {
  type: string;
  aggregateId: string;
  version: number;
}

export class ApiError extends Error {
  constructor(public readonly status: number, message: string) {
    super(message);
    this.name = 'ApiError';
  }
}

export interface ClientOptions {
  /** Backend origin, e.g. https://api.example.com (default: same origin). */
  baseUrl?: string;
  tenantId?: string;
  fetch?: typeof fetch;
}

export interface ExecuteOptions {
  /** Sent as X-Idempotency-Key so retries are safe. */
  idempotencyKey?: string;
}

export function createCheckoutAutenticadoConLaravelSanctumEInertiaVueClient(options: ClientOptions = {}) {
  const baseUrl = (options.baseUrl ?? '').replace(/\/$/, '');
  const doFetch = options.fetch ?? ((...args: Parameters<typeof fetch>) => fetch(...args));

  async function execute(id: string, command: CommandName, payload: Record<string, unknown> = {}, opts: ExecuteOptions = {}): Promise<CommandResult> {
    const headers: Record<string, string> = { 'Content-Type': 'application/json', Accept: 'application/json' };
    if (options.tenantId) headers['X-Tenant-Id'] = options.tenantId;
    if (opts.idempotencyKey) headers['X-Idempotency-Key'] = opts.idempotencyKey;

    const res = await doFetch(`${baseUrl}/api/v1/checkout-autenticado-con-laravel-sanctum-e-inertia-vue/${encodeURIComponent(id)}/${command}`, {
      method: 'POST',
      headers,
      body: JSON.stringify(payload)
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok) throw new ApiError(res.status, (body as { detail?: string }).detail ?? `Request failed with status ${res.status}`);
    return body as CommandResult;
  }

  return {
    execute,
    processCheckoutAutenticadoConLaravelSanctumEInertiaVue: (id: string, payload?: Record<string, unknown>, opts?: ExecuteOptions) => execute(id, 'process_checkout_autenticado_con_laravel_sanctum_e_inertia_vue', payload, opts),
  };
}

export type CheckoutAutenticadoConLaravelSanctumEInertiaVueClient = ReturnType<typeof createCheckoutAutenticadoConLaravelSanctumEInertiaVueClient>;
