<?php

declare(strict_types=1);

use App\Domain\CheckoutAutenticadoConLaravelSanctumEInertiaVue\CheckoutAutenticadoConLaravelSanctumEInertiaVueAggregate;
use Behat\Behat\Context\Context;
use Behat\Behat\Tester\Exception\PendingException;

/**
 * Behat context for "Checkout Autenticado con Laravel Sanctum e Inertia Vue" (generated by gherkin-ai).
 * Steps are wired to the feature and pending until implemented (non-strict runs do not fail).
 */
final class CheckoutAutenticadoConLaravelSanctumEInertiaVueContext implements Context
{
    private CheckoutAutenticadoConLaravelSanctumEInertiaVueAggregate $aggregate;

    /** @BeforeScenario */
    public function resetAggregate(): void
    {
        $this->aggregate = new CheckoutAutenticadoConLaravelSanctumEInertiaVueAggregate('scenario-aggregate');
    }

    /**
     * @Given /^que un usuario está autenticado con sesión de Laravel Sanctum$/
     */
    public function givenQueUnUsuarioEstaAutenticadoConSesionDeLaravelSanctum(): void
    {
        // Pending: drive $this->aggregate (or the HTTP API) and assert the outcome.
        throw new PendingException();
    }

    /**
     * @When /^completa el formulario de pago en la vista Vue 3 de Inertia$/
     */
    public function whenCompletaElFormularioDePagoEnLaVistaVue3DeInertia(): void
    {
        // Pending: drive $this->aggregate (or the HTTP API) and assert the outcome.
        throw new PendingException();
    }

    /**
     * @When /^se envía la petición `Inertia\.post\('\/orders', payload\)`$/
     */
    public function whenSeEnviaLaPeticionInertiaPostOrdersPayload(): void
    {
        // Pending: drive $this->aggregate (or the HTTP API) and assert the outcome.
        throw new PendingException();
    }

    /**
     * @Then /^el `StoreOrderRequest` de Laravel valida la carga útil$/
     */
    public function thenElStoreOrderRequestDeLaravelValidaLaCargaUtil(): void
    {
        // Pending: drive $this->aggregate (or the HTTP API) and assert the outcome.
        throw new PendingException();
    }

    /**
     * @Then /^se crea la orden en la base de datos de forma transaccional$/
     */
    public function thenSeCreaLaOrdenEnLaBaseDeDatosDeFormaTransaccional(): void
    {
        // Pending: drive $this->aggregate (or the HTTP API) and assert the outcome.
        throw new PendingException();
    }

    /**
     * @Then /^Inertia redirige a la página de éxito `orders\.show` renderizando componentes Vue$/
     */
    public function thenInertiaRedirigeALaPaginaDeExitoOrdersShowRenderizandoComponentes_(): void
    {
        // Pending: drive $this->aggregate (or the HTTP API) and assert the outcome.
        throw new PendingException();
    }
}
