/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: Checkout Autenticado con Laravel Sanctum e Inertia Vue
   Generated by gherkin-ai CLI
   ========================================================================== */

export interface CheckoutAutenticadoconLaravelSanctumeInertiaVueFixture {
  id: string;

}

export function createCheckoutAutenticadoconLaravelSanctumeInertiaVueFixture(): CheckoutAutenticadoconLaravelSanctumeInertiaVueFixture {
  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',

  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [

];
