/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: Checkout Autenticado con Laravel Sanctum e Inertia Vue
   Generated by gherkin-ai CLI
   ========================================================================== */

export interface CheckoutAutenticadoConLaravelSanctumEInertiaVueFixture {
  id: string;

}

export function createCheckoutAutenticadoConLaravelSanctumEInertiaVueFixture(): CheckoutAutenticadoConLaravelSanctumEInertiaVueFixture {
  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',

  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
  "que un usuario está autenticado con sesión de Laravel Sanctum"
];
